export const mediaRef = document.querySelector('.js-media-container');
export const formRef = document.querySelector('.js-search-form');
export const modalRef = document.querySelector('.js-modal');
export const movieRef = document.querySelector('.js-movie');
export const closeModal = document.querySelector('[data-action="close-modal"]');
export const backdrop = document.querySelector('[data-backdrop]');
export const activeNavLink = document.querySelector('.navigation .list-navigation');
export const errorTextForSearchForm = document.querySelector('.form-text-error');
export const homeNavLinkRef = document.querySelector('#home');
export const movieNavLinkRef = document.querySelector('#myMovies');
export const headerRef = document.querySelector('.header');
export const wrapBtnLibRef = document.querySelector('.wrapper-for-library');
export const searchMovie = document.querySelector('.search-container');
export const watchedBtn = document.querySelector('.header-button-watched');
export const queueBtn = document.querySelector('.header-button-queue');
export const saveWatchedModalBtnRef = document.querySelector('.button-modal-watch');